name: pb_env
dependencies:
- python =3.6.5
- taxcalc =0.20.1
- btax =0.2.2
- numba >=0.33.0
- pandas >=0.22.0
- bokeh =0.12.7
- nomkl
- gevent
- pillow
- pyparsing

channels:
  - ospc
  - ospc/label/dev
  - defaults
  - conda-forge
