version: '3'
services:
  flask:
    image: "opensourcepolicycenter/flask:${TAG}"
    ports:
      - 5050:5050
    depends_on:
      - redis
      - celery
  celery:
    image: "opensourcepolicycenter/celery:${TAG}"
    depends_on:
      - redis
  redis:
    image: redis
