apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o simple.yml
      kompose.version: 1.10.0 (8bb0907)
    creationTimestamp: null
    labels:
      io.kompose.service: celery
    name: celery
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: celery
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o simple.yml
      kompose.version: 1.10.0 (8bb0907)
    creationTimestamp: null
    labels:
      io.kompose.service: flask
    name: flask
  spec:
    type: NodePort
    ports:
    - name: "5050"
      port: 5050
      targetPort: 5050
    selector:
      io.kompose.service: flask
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o simple.yml
      kompose.version: 1.10.0 (8bb0907)
    creationTimestamp: null
    labels:
      io.kompose.service: redis
    name: redis
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: redis
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o simple.yml
      kompose.version: 1.10.0 (8bb0907)
    creationTimestamp: null
    labels:
      io.kompose.service: celery
    name: celery
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: celery
      spec:
        containers:
        - image: gcr.io/policybrain/celery:latest
          name: celery
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o simple.yml
      kompose.version: 1.10.0 (8bb0907)
    creationTimestamp: null
    labels:
      io.kompose.service: flask
    name: flask
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: flask
      spec:
        containers:
        - image: gcr.io/policybrain/flask:latest
          name: flask
          ports:
          - containerPort: 5050
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o simple.yml
      kompose.version: 1.10.0 (8bb0907)
    creationTimestamp: null
    labels:
      io.kompose.service: redis
    name: redis
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: redis
      spec:
        containers:
        - image: redis
          name: redis
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}
